version: '3.8'

services:
  bot-db:
    image: postgres:14.1-alpine
    container_name: pgdb-bot
    restart: always
    environment:
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot2
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata

  web:
    container_name: web-server
    build: .
    depends_on:
      - bot-db
    environment:
      PGHOST_DB: bot-db
    ports:
      - 3000:3000
    # volumes:
    #   - ./src:/usr/src/app
