version: '3.8'

services:
#  web:
#   container_name: web-server
#   build: .
#   depends_on:
#     - bot-db
#   environment:
#     PGHOST_DB: bot-db
#   ports:
#     - 3000:3000
#   volumes:
#   - ./:/usr/src/app